# Generated by Django 5.2 on 2025-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0002_remove_category_sub_cat_article_slug_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/linked_images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
