# Generated by Django 5.2 on 2025-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0003_linkedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('localisation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebPlatforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('identification', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
