# Generated by Django 6.0 on 2026-01-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0007_pendingevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
