# Generated by Django 6.0 on 2026-01-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0008_article_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rank',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
