# Generated by Django 6.0 on 2026-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0011_alter_participant_email_alter_participant_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='max_participants',
            field=models.IntegerField(default=-1, verbose_name='Nombre maximum de participants (-1 pour participants illimités)'),
        ),
    ]
