# Generated by Django 5.2.8 on 2026-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0012_events_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='articles_pdfs/', verbose_name='Document PDF'),
        ),
    ]
