# Generated by Django 6.0 on 2026-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0013_article_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='know_from',
            field=models.TextField(blank=True, verbose_name='Comment avez-vous connu JeBiF ?'),
        ),
    ]
