# Generated by Django 5.2.8 on 2026-04-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0013_article_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='nb_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='know_from',
            field=models.TextField(blank=True, verbose_name='Comment avez-vous connu JeBiF ?'),
        ),
    ]
