# Generated by Django 5.2.8 on 2026-04-20 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0014_events_nb_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='image_use',
            field=models.BooleanField(default=True, verbose_name="Autorisation d'utiliser l'image"),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(),
        ),
    ]
