# Generated by Django 5.2.8 on 2026-04-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0015_participant_image_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='k_f_text',
            field=models.CharField(blank=True, verbose_name='Si Autre:'),
        ),
        migrations.AddField(
            model_name='participant',
            name='know_from',
            field=models.CharField(blank=True, choices=[('DIS', 'Discord'), ('LIN', 'LinkedIN'), ('MAI', 'Mail'), ('ACQ', 'Bouche-à-oreille'), ('OTH', 'Autre')], max_length=3, verbose_name='Comment avez-vous pris connaissance de cet événement?'),
        ),
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
