# Generated by Django 6.0 on 2026-04-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0015_events_time_alter_events_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
