# Generated by Django 6.0 on 2026-04-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0016_remove_events_time_alter_events_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='know_from_options',
            field=models.TextField(blank=True, verbose_name="Options d'origine supplémentaires"),
        ),
        migrations.AlterField(
            model_name='participant',
            name='know_from',
            field=models.TextField(blank=True, verbose_name='Comment avez-vous découvert cet évènement ?'),
        ),
    ]
