# Generated by Django 5.2.8 on 2026-04-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0017_remove_events_nb_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='featured',
            new_name='is_draft',
        ),
    ]
