# Generated by Django 6.0 on 2026-04-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0018_alter_participant_know_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='know_from_options',
        ),
    ]
