# Generated by Django 5.2.8 on 2026-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0018_rename_featured_article_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('kind', models.CharField(blank=True, choices=[('CA', "Conseil d'administration"), ('GT', 'Groupe de Travail'), ('AG', 'Assemblée Générale'), ('OT', 'Autre')], max_length=2, verbose_name='Type de réunion')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
