# Generated by Django 5.2.8 on 2026-04-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_website', '0019_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='color',
            field=models.CharField(blank=True, choices=[('CA', 'red'), ('GT', 'blueviolet'), ('AG', 'green'), ('OT', 'brown')], max_length=2, verbose_name='Couleur'),
        ),
    ]
