# Generated by Django 5.2 on 2025-08-23 15:56

import datetime
import django.db.models.deletion
import jebif_users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MembershipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=75, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=75, verbose_name='Nom')),
                ('laboratory_name', models.CharField(max_length=75, verbose_name='Laboratoire')),
                ('laboratory_city', models.CharField(max_length=75, verbose_name='Ville')),
                ('laboratory_cp', models.CharField(max_length=7, verbose_name='Code Postal')),
                ('laboratory_country', models.CharField(max_length=75, verbose_name='Pays')),
                ('position', models.CharField(max_length=75, verbose_name='Poste actuel')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation pour adhérer')),
                ('inscription_date', models.DateField(default=datetime.date.today)),
                ('active', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membre',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField(default=jebif_users.models.end_membership)),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jebif_users.membershipinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipInfoEmailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('old_email', models.EmailField(max_length=254)),
                ('info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jebif_users.membershipinfo')),
            ],
        ),
    ]
