# Generated by Django 5.2 on 2025-08-31 19:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='membershipinfoemailchange',
            name='info',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstname', models.CharField(max_length=75, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=75, verbose_name='Nom')),
                ('laboratory', models.CharField(max_length=75, verbose_name='Laboratoire')),
                ('city_name', models.CharField(max_length=75, verbose_name='Ville')),
                ('city_cp', models.CharField(max_length=7, verbose_name='Code Postal')),
                ('country', models.CharField(max_length=75, verbose_name='Pays')),
                ('position', models.CharField(max_length=75, verbose_name='Poste actuel')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation pour adhérer')),
                ('inscription_date', models.DateField(default=datetime.date.today)),
                ('is_member', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('begin_membership', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserInfo',
            },
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='MembershipInfo',
        ),
        migrations.DeleteModel(
            name='MembershipInfoEmailChange',
        ),
    ]
