# Generated by Django 5.2 on 2025-08-31 20:05

import jebif_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_users', '0002_remove_membershipinfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='end_membership',
            field=models.DateField(default=jebif_users.models.default_end_membership),
        ),
    ]
