# Generated by Django 5.2 on 2025-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_users', '0003_userinfo_end_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='want_member',
            field=models.BooleanField(default=True),
        ),
    ]
