# Generated by Django 5.2 on 2025-09-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_users', '0004_userinfo_want_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='want_member',
            field=models.BooleanField(default=False, verbose_name='Veux-tu adhérer / renouveller ton adhésion?'),
        ),
    ]
