# Generated by Django 5.2 on 2025-09-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_users', '0005_alter_userinfo_want_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='want_member',
            field=models.BooleanField(default=False, verbose_name="L'utilisateur souhaite devenir adhérent"),
        ),
    ]
