# Generated by Django 6.0 on 2026-02-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_users', '0006_alter_userinfo_want_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
