# Generated by Django 5.2.8 on 2026-03-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_users', '0007_userinfo_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='know_from',
            field=models.TextField(blank=True, verbose_name="Comment a connu l'asso"),
        ),
    ]
