# Generated by Django 5.2.8 on 2026-03-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_users', '0008_userinfo_know_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='know_from',
            field=models.TextField(blank=True, max_length=200, verbose_name='Comment avez vous connu JeBiF ?'),
        ),
    ]
