# Generated by Django 5.2 on 2025-09-11 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=50, verbose_name='Libellé')),
                ('max_choices', models.PositiveSmallIntegerField()),
                ('min_choices', models.PositiveSmallIntegerField(default=0)),
                ('intro', models.TextField(verbose_name='Introduction')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Libellé')),
                ('description', models.TextField(verbose_name='Description')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidats', to='jebif_election.election')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='jebif_election.candidates')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='jebif_election.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
