# Generated by Django 5.2 on 2025-09-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='choix',
            field=models.CharField(choices=[('OUI', 'Oui'), ('NON', 'Non'), ('ABST', "S'abstient")], default='ABST', max_length=10),
        ),
    ]
