# Generated by Django 5.2 on 2025-09-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0002_vote_choix'),
        ('jebif_users', '0006_alter_userinfo_want_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='jebif_users.userinfo'),
        ),
    ]
