# Generated by Django 5.2 on 2025-09-12 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0003_alter_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='date',
            field=models.DateTimeField(default=datetime.date(2025, 9, 12)),
        ),
    ]
