# Generated by Django 5.2 on 2025-09-16 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0004_election_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
