# Generated by Django 5.2 on 2025-09-16 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0005_election_ended_election_waiting_alter_election_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Libellé')),
                ('description', models.TextField(verbose_name='Description')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_candidats', to='jebif_election.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
