# Generated by Django 5.2 on 2025-09-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0006_pendingcandidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcandidates',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
