# Generated by Django 5.2 on 2025-09-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0007_pendingcandidates_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='pdffile',
            field=models.FileField(blank=True, null=True, upload_to='elections_pdfs/', verbose_name='Document PDF'),
        ),
    ]
