# Generated by Django 5.2 on 2025-09-20 13:40

import jebif_election.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0008_candidates_pdffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_date',
            field=models.DateTimeField(default=jebif_election.models.default_end),
        ),
    ]
