# Generated by Django 5.2 on 2025-09-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0009_election_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='date',
            new_name='start_date',
        ),
    ]
