# Generated by Django 5.2 on 2025-09-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jebif_election', '0010_rename_date_election_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='max_choices',
        ),
        migrations.RemoveField(
            model_name='election',
            name='min_choices',
        ),
    ]
